### ISSUE TITLE
scale_colour_grad_poisson() is a little too washed out at the lower end

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/poispalette#60]
<img width="646" alt="Screenshot 2023-01-14 at 12 05 13" src="https://user-images.githubusercontent.com/613671/212494202-69c00b8a-6d7b-4f14-9fee-f1991ef28e8b.png">

**Comment by joethorley** [comment]
I'm wondering if this is my screen settings

This is a screenshot

**Comment by evanamiesgalonski** [comment]
agreed that does look a little too faint, il adjust

**Comment by evanamiesgalonski** [comment]
fa4e7892a5606a37beda1d1c2269442db4cbd2ba
