### ISSUE TITLE
And the discrete scale is a little too hard to distinguish black and blue.

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/poispalette#61]
<img width="647" alt="Screenshot 2023-01-14 at 12 25 45" src="https://user-images.githubusercontent.com/613671/212495132-ec9a6da8-31f4-4165-bd07-7eb676acbbff.png">

**Comment by joethorley** [comment]
I'm wondering if this is my screen settings

**Comment by joethorley** [comment]
Its a screenshot

**Comment by evanamiesgalonski** [comment]
lightening the blue resulted in too much similarity to our turquoise. i think the solution is to remove the turquoise and have 1 less discrete colour. i also had to shift our red and yellow slightly lighter to make sure the first 4 colours still accommodate  all types of colour blindness.
<img width="1021" alt="Screen Shot 2023-01-16 at 15 05 33" src="https://user-images.githubusercontent.com/14318875/212777874-e7d3c672-d255-4efc-8305-d94ee6c816c1.png">

**Comment by joethorley** [comment]
These are really nice - I like those a lot.

**Comment by evanamiesgalonski** [comment]
great - e954abfa4735bf9feabebd3da7aeb8abd40578c1
