### ISSUE TITLE
`scale_color_disc_poisson("KelpLine") ` uses blank for NAs when a color would be preferable

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/poispalette#63]
<img width="108" alt="Screenshot 2023-03-30 at 09 43 00" src="https://user-images.githubusercontent.com/613671/228906567-9a0d590b-71af-4162-af7b-185fbec9dbf2.png">

**Comment by evanamiesgalonski** [comment]
fixed a12073760aac769726a476bb9a09c04593a1b51d
